FROM ubuntu:latest
MAINTAINER Ocean Proteins Webmaster "webmaster@ocean-proteins.org"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
